apiVersion: v1
kind: Pod
metadata:
    name: aplicacao
spec:
  containers:
    - name: b-eventos
      image: b-eventos
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
      resources:
        limits:
          memory: 256Mi
    - name: mss-a1
      image: mss-a1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8082
      resources:
        limits:
          memory: 256Mi
    - name: mss-a2
      image: mss-a2
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8081
      resources:
        limits:
          memory: 256Mi
    - name: frontend
      image: frontend
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3000